spring:
  application:
    name: nacos-consumer-feign
  cloud:
    nacos:
      discovery:
        server-addr: 10.86.85.157:8848

server:
  port: 9092

management:
  endpoints:
    web:
      exposure:
        include: "*"